plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'R-project'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

// 프론트 빌드 task
task npmInstall(type: Exec) {
    workingDir 'frontend'
    commandLine 'npm', 'install'
}

task npmBuild(type: Exec) {
    dependsOn npmInstall
    workingDir 'frontend'
    commandLine 'npm', 'run', 'build'
}

// Spring Boot 빌드 전에 프론트 빌드 실행
processResources.dependsOn npmBuild

// 프론트 빌드 결과물을 static으로 복사
task copyFrontend(type: Copy) {
    dependsOn npmBuild
    from 'frontend/dist'
    into 'src/main/resources/static'
}

processResources.dependsOn copyFrontend

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'com.mysql:mysql-connector-j'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    testImplementation 'org.springframework.security:spring-security-test'
}